# Generated by Django 5.2.17 on 2026-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['completed_at'], name='pomo_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'due_time'], name='task_due_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['reminder_at'], name='task_reminder_at_idx'),
        ),
    ]
