# Generated by Django 5.2.17 on 2026-10-06 12:24

from datetime import timedelta

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_legacy_recurring_schedules(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    RecurringSchedule = apps.get_model("tasks", "RecurringSchedule")
    today = django.utils.timezone.localdate()
    for task in Task.objects.exclude(recurrence="none").iterator():
        starts_on = task.due_date or django.utils.timezone.localtime(task.created_at).date()
        weekdays = [starts_on.weekday()] if task.recurrence == "custom" else []
        RecurringSchedule.objects.get_or_create(
            template_id=task.pk,
            defaults={
                "frequency": task.recurrence,
                "weekdays": weekdays,
                "starts_on": starts_on,
                "last_generated_through": today - timedelta(days=1),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_pomodorosession_pomo_completed_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reminder', 'Task reminder'), ('overdue', 'Task overdue')], default='reminder', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Selected days')], max_length=10)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('starts_on', models.DateField()),
                ('last_generated_through', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TaskExtensionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_type', models.CharField(choices=[('duration', 'Duration'), ('tomorrow', 'Tomorrow'), ('custom', 'Custom duration')], max_length=12)),
                ('minutes', models.PositiveIntegerField()),
                ('previous_due_at', models.DateTimeField(blank=True, null=True)),
                ('extended_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('started_at',),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='task',
            name='deliverable_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='occurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_interval_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Selected days')], default='none', max_length=10),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['recurring_template', 'occurrence_date'], name='task_template_occurrence_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_template__isnull', False)), fields=('recurring_template', 'occurrence_date'), name='unique_task_template_occurrence'),
        ),
        migrations.AddField(
            model_name='desktopnotification',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_notifications', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedule', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskextensionhistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_history', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='tasktimeentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tasks.task'),
        ),
        migrations.RunPython(create_legacy_recurring_schedules, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='tasktimeentry',
            index=models.Index(fields=['task', 'ended_at'], name='task_time_active_idx'),
        ),
    ]
