# Generated by Django 5.2.17 on 2026-10-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_enhanced_task_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
